// For testing the HTML files outside of the app.

var FatWatch={
	"deviceName":"Ben\u2019s Mac",
	"deviceModel":"MacBook Jr",
	"version":"1.5\u2202",
	"copyright":"FatWatch 1.5\u2202 (0) 2008-2009 Benjamin Ragheb",
	"dateFormats":[{"value":"y-MM-dd",
				   "label":"2009-12-14"},
				   {"value":"M/d/yy",
					"label":"12/14/09"}],
	"weightFormats":[{"value":"0", "label":"pounds (lb)"},
					 {"value":"1", "label":"kilograms (kg)"},
					 {"value":"2", "label":"grams (g)"}],
	"fatFormats":[{"value":"0", "label":"percent (0%&ndash;100%)"},
				  {"value":"1", "label":"ratio (0.0&ndash;1.0)"}],
	"exportDefaults":{
		"exportDate":true,
		"exportDateName":"Date",
		"exportDateFormat":"y-MM-dd",
		"exportWeight":true,
		"exportWeightName":"Weight",
		"exportWeightFormat":"1",
		"exportTrendWeight":false,
		"exportTrendWeightName":"Trend",
		"exportFat":false,
		"exportFatName":"BodyFat",
		"exportFatFormat":"0",
		"exportFlag0":true,
		"exportFlag0Name":"Checkmark",
		"exportFlag1":true,
		"exportFlag1Name":"Checkmark2",
		"exportFlag2":false,
		"exportFlag2Name":"Checkmark3",
		"exportFlag3":true,
		"exportFlag3Name":"Checkmark4",
		"exportNote":true,
		"exportNoteName":"Note"
	}
};