// For testing the HTML files outside of the app.

var FatWatch={
	"deviceName":"Ben’s Mac",
	"deviceModel":"MacBook Jr",
	"version":"1.5∂",
	"copyright":"FatWatch 1.5∂ (0) 2008-2009 Benjamin Ragheb",
	"dateFormats":[{"value":"y-MM-dd",
				   "label":"2009-12-14"},
				   {"value":"M/d/yy",
					"label":"12/14/09"}],
	"weightFormats":[{"value":"L", "label":"pounds (lb)"},
					 {"value":"K", "label":"kilograms (kg)"},
					 {"value":"G", "label":"grams (g)"}],
	"fatFormats":[{"value":"R", "label":"ratio (0.0&ndash;1.0)"},
				  {"value":"P", "label":"percent (0%&ndash;100%)"}],
	"exportDefaults":{
		"exportDate":true,
		"exportDateName":"Date",
		"exportDateFormat":"y-MM-dd",
		"exportWeight":true,
		"exportWeightName":"Weight",
		"exportWeightFormat":"K",
		"exportTrendWeight":false,
		"exportTrendWeightName":"Trend",
		"exportFat":false,
		"exportFatName":"BodyFat",
		"exportFatFormat":"percent",
		"exportFlag1":true,
		"exportFlag1Name":"Checkmark",
		"exportFlag2":true,
		"exportFlag2Name":"Checkmark2",
		"exportFlag3":false,
		"exportFlag3Name":"Checkmark3",
		"exportFlag4":true,
		"exportFlag4Name":"Checkmark4",
		"exportNote":true,
		"exportNoteName":"Note"
	}
};